// Master slick model: every non-redundant piece of the four models on one coastal grid.
//
//   from the two-layer model   water layer (tide, wind, Coriolis, friction, headland coast), oil-layer thickness and
//                              momentum (reduced-gravity spreading, drag towards the surface drift, fronts), coast walls
//                              and stranding                                                       → transport core
//   from the thin-film model   film rupture below the terminal thickness (negative diffusion + hyperdiffusion), K_h,
//                              weathering. Its gravity–viscous spreading is dropped: the oil momentum equation already
//                              contains it (drag-dominated limit)                                  → operator-split flux
//   from the VOF section       breaker entrainment rate per wind speed, precomputed offline (ENTRAINMENT_TABLE);
//                              a share of it stays dispersed                                       → natural dispersion
//   from the phase-field model breakup and coalescence are already produced by rupture, so the solver is dropped; its
//                              resolution check is applied to the rupture wavelength (≥ 6 cells)
//   shared flow                windage (incl. wave drift), Langmuir windrows, eddies
import { Budget, volume, type MapModel, type ParamSpec } from './grid';
import { FLOW_SPEC } from './flow';
import { CoastalCore, SHELF_SPEC, TWO_LAYER_DEFAULTS } from './twolayer';
import { FilmFlux, OIL_SPEC, RUPTURE_SPEC, filmWarnings, oilDrift, slickRows, type FilmFluxParams } from './thinfilm';
import { OilLayer } from './twolayer';
import { breakingShare, seaHeight } from './vof';
import type { ForcingRegion, Polygon, SlickProfile } from './shapes';

/** Breaker entrainment rate (s⁻¹) vs 10 m wind (m/s), generated by `npm run vof-table` from the VOF section model. */
export const ENTRAINMENT_TABLE: [number, number][] = [[4, 5.595e-6], [6, 1.376e-5], [8, 1.556e-5], [10, 1.471e-5], [12, 2.535e-5], [15, 5.868e-5], [20, 1.102e-4]];

export function entrainmentAt(U10: number): number {
  const T = ENTRAINMENT_TABLE;
  if (U10 <= T[0][0]) return (T[0][1] * Math.max(0, U10)) / T[0][0];
  for (let i = 1; i < T.length; i++) if (U10 <= T[i][0]) { const w = (U10 - T[i - 1][0]) / (T[i][0] - T[i - 1][0]); return T[i - 1][1] + w * (T[i][1] - T[i - 1][1]); }
  return T[T.length - 1][1];
}

export const MASTER_DEFAULTS = {
  ...TWO_LAYER_DEFAULTS,
  eddySpeed: 0.03, eddyScaleM: 2000,
  Kh: 0.3, hTerminalUm: 40, lensD: 1.5, lensWavelengthM: 320,
  permanentShare: 0.2,
};

export const MASTER_SPEC: ParamSpec[] = [
  ...OIL_SPEC.filter((s) => s.key !== 'dispersionRate'),
  { key: 'permanentShare', label: 'Share of entrained oil staying dispersed', unit: '', min: 0, max: 1, step: 0.05, assumption: true },
  { key: 'Kh', label: 'Turbulent diffusivity K_h', unit: 'm²/s', min: 0, max: 10, step: 0.1, assumption: true },
  ...RUPTURE_SPEC, ...SHELF_SPEC, ...FLOW_SPEC,
];

export class MasterModel implements MapModel {
  readonly kind = 'map';
  readonly id = 'master';
  readonly title = 'Master (combined)';
  readonly info = {
    calculates: 'One coastal slick with everything that is not redundant: water layer and oil-layer momentum from the two-layer model (tide, fronts, coast, stranding), film rupture into patches and turbulent diffusion from the thin-film model, breaker-driven natural dispersion from the VOF section, windrows and eddies, evaporation.',
    assumptions: 'Everything synthetic stays synthetic: coast, bathymetry, tide, flow features, rupture and entrainment coefficients are tunable assumptions. The entrainment table comes from the VOF model offline (npm run vof-table); a share of entrained oil is assumed to stay dispersed.',
    master: 'Dropped: thin-film spreading (duplicated by oil momentum), the phase-field solver (duplicated by rupture), the particle-model constant dispersion rate (replaced by the VOF table). Kept: the phase-field resolution check on the rupture wavelength.',
  };
  readonly spec = MASTER_SPEC;
  readonly params = { ...MASTER_DEFAULTS } as typeof MASTER_DEFAULTS & Record<string, number>;
  readonly speeds = [60, 300, 900, 1800];
  readonly core = new CoastalCore(this.params);
  private film = new FilmFlux(256, 256);
  private before = new Float64Array(256 * 256);
  readonly supportsRegions = true;

  get frame() { return this.core.frame; }
  get t() { return this.core.t; }
  set t(v: number) { this.core.t = v; }
  get rhoOil() { return this.params.oilDensity; }
  get sheenM() { return this.params.sheenUm * 1e-6; }
  get budget(): Budget { return this.core.budget; }

  constructor(params: Partial<typeof MASTER_DEFAULTS> = {}) {
    Object.assign(this.params, params);
    this.reset();
  }

  reset() { this.core.reset(); }
  setRegions(r: ForcingRegion[]) { this.core.setRegions(r); }
  addOil(poly: Polygon, v: number, profile: SlickProfile, replace: boolean) { return this.core.addOil(poly, v, profile, replace); }

  filmParams(): FilmFluxParams {
    const p = this.params;
    // the sheen lag is in the oil-layer drift target (CoastalCore); only shear dispersion is a film flux here
    return { gPrime: this.core.gPrime(), spreadC: p.spreadC, Kh: p.Kh, hTerminal: p.hTerminalUm * 1e-6, lensD: p.lensD, lensWavelengthM: p.lensWavelengthM, ...oilDrift(this.core.flow), lag: 0 };
  }

  dispersionRate(): number {
    return this.params.permanentShare * entrainmentAt(this.params.windSpeed);
  }

  step(dt: number) {
    const o = this.core.oil, fp = this.filmParams(), dx = this.frame.dx;
    this.core.advance(dt, () => this.dispersionRate(), (sub) => {
      // rupture + K_h as mass fluxes after the momentum step; velocity is kept, so momentum follows the moved mass
      let hMax = 0;
      for (const v of o.h) if (v > hMax) hMax = v;
      const n = Math.max(1, Math.ceil(sub / this.film.dtLimit(hMax, dx, fp, false)));
      this.before.set(o.h);
      for (let s = 0; s < n; s++) this.core.budget.left += this.film.apply(o.h, dx, sub / n, fp, false, o.land, null, null);
      for (let k = 0; k < o.h.length; k++) {
        const b = this.before[k];
        if (b > OilLayer.DRY) { const r = o.h[k] / b; o.qx[k] *= r; o.qy[k] *= r; } else { o.qx[k] = 0; o.qy[k] = 0; }
      }
    });
  }

  thickness() { return this.core.oil.h; }
  land() { return this.core.oil.land; }
  arrows() { return this.core.arrows(); }

  stats(): [string, string][] {
    const U = this.params.windSpeed;
    return [
      ...slickRows(this),
      ['sea state (VOF table)', `H ${seaHeight(U).toFixed(2)} m, ${(100 * breakingShare(U)).toFixed(1)}% crests breaking, entrainment ${entrainmentAt(U).toExponential(2)} s⁻¹`],
      ['natural dispersion', `${this.dispersionRate().toExponential(2)} s⁻¹ (${this.params.permanentShare} of entrainment)`],
      ...this.core.rows(),
      ...this.core.budget.rows(volume(this.core.oil.h, this.frame.dx)),
    ];
  }

  warnings(): string[] {
    return filmWarnings(this, this.core.budget, volume(this.core.oil.h, this.frame.dx), this.params.lensWavelengthM);
  }
}
